export async function GET(req: Consorcio) {
  const data: String[] = [
    `O que é um consórcio e como ele se diferencia de um financiamento? O consórcio é uma modalidade de compra planejada em que um grupo de pessoas se une para formar uma poupança conjunta destinada à aquisição de bens ou serviços. A principal vantagem é a ausência de juros. Em vez de pagar juros a um banco, o participante contribui para um fundo comum. Diferentemente do financiamento, que é um empréstimo com juros para aquisição imediata, o consórcio funciona como uma "poupança programada", resultando em parcelas geralmente mais acessíveis. A Rodobens atua como administradora, gerenciando os recursos do grupo, organizando as assembleias e garantindo a conformidade com as regras do Banco Central do Brasil.`,
    `O consórcio Rodobens é realmente "sem juros"? Quais são todos os custos envolvidos? Sim, é correto afirmar que o consórcio não possui juros. No entanto, existem outros custos. O principal é a Taxa de Administração, um percentual fixo sobre o valor total da carta de crédito, diluído nas parcelas mensais. Este valor remunera a Rodobens pela gestão do grupo. Além dela, pode haver a cobrança de um Fundo de Reserva, que serve como um seguro para cobrir eventuais inadimplências no grupo, garantindo sua saúde financeira. Alguns planos também podem incluir seguros específicos. É fundamental ler o contrato de adesão para verificar todos os custos aplicáveis, pois a Rodobens oferece planos com e sem taxa de adesão e fundo de reserva.",O valor da minha parcela será sempre o mesmo até o final do plano? Não necessariamente. O valor da carta de crédito e, consequentemente, das parcelas, passa por reajustes periódicos baseados em índices de inflação, como o INCC para imóveis ou o IPCA para veículos. O objetivo desses reajustes é preservar o poder de compra da sua carta de crédito ao longo do tempo, garantindo que você consiga adquirir o bem desejado mesmo com o aumento dos preços no mercado. Portanto, embora não existam juros, o valor da parcela mensal pode aumentar durante a vigência do contrato, o que desafia a percepção de um pagamento totalmente fixo e previsível. A simulação inicial é apenas um ponto de partida.`,
    `Como faço para ser contemplado e receber a carta de crédito? A contemplação é o momento em que você adquire o direito de usar a carta de crédito. Existem duas formas principais para isso acontecer: sorteio e lance. No sorteio, realizado mensalmente nas assembleias, todos os participantes com as parcelas em dia têm a mesma chance de serem escolhidos. Os sorteios são baseados nos resultados da Loteria Federal, garantindo a transparência do processo. Este método exige paciência, pois a contemplação pode ocorrer em qualquer mês, do início ao fim do plano. A segunda forma é a oferta de um lance, que funciona como uma estratégia para antecipar a contemplação.`,
    `Como funcionam os lances para acelerar a contemplação? O lance é um adiantamento de parcelas futuras, e a maior oferta geralmente vence. Existem três modalidades principais: 1) Lance Livre: Você oferece o valor que desejar, e a maior oferta vence. É ideal para quem tem capital disponível para antecipar um número significativo de parcelas. 2) Lance Fixo: Você oferece um percentual pré-determinado no contrato (ex: 25%). Como várias pessoas podem ofertar o mesmo valor, o vencedor é decidido por sorteio entre os ofertantes. 3) Lance Embutido: Permite usar parte do valor da sua própria carta de crédito para compor o lance. Embora torne a oferta mais acessível, o valor utilizado é descontado da carta de crédito final que você receberá.`,
    `O que é o "Plano Pontual" da Rodobens? Ele garante a contemplação? O "Plano Pontual" é um produto exclusivo da Rodobens que oferece maior previsibilidade, prometendo a aquisição do bem após o pagamento de um número específico de parcelas, sem depender de sorteio ou lance. No entanto, o mecanismo por trás dele é uma operação de financiamento em parceria com o Banco Rodobens. O banco adianta o valor para o cliente adquirir o bem. O consorciado continua pagando as parcelas do consórcio e, quando sua cota for finalmente contemplada no futuro, a carta de crédito é usada para quitar o financiamento com o banco. É importante notar que, por ser uma operação de crédito, o cliente precisa passar por uma análise e aprovação de crédito do Banco Rodobens.`,
    `Fui contemplado no sorteio! Já posso usar a carta de crédito imediatamente? Não. A contemplação é a primeira etapa, mas não a final. Após ser contemplado (seja por sorteio ou lance), você precisará passar por uma análise cadastral e de crédito. A administradora realiza essa verificação para garantir que você terá condições de continuar pagando as parcelas restantes até o fim do plano, protegendo assim a saúde financeira de todo o grupo. Muitos consumidores desconhecem essa etapa, mas ela é crucial. Uma situação financeira adversa (como perda de emprego) pode levar à reprovação do crédito, mesmo após a contemplação, impedindo a liberação da carta.`,
    `Meu crédito foi aprovado após a contemplação. Como uso a carta de crédito? Com o crédito aprovado, o processo é gerenciado pela plataforma digital da Rodobens. Você indica o bem que deseja adquirir e envia a documentação necessária. Você tem liberdade para escolher o vendedor, e a Rodobens efetua o pagamento diretamente a ele. Se o valor do bem for maior que a carta de crédito, você deve pagar a diferença. Se for menor, o saldo restante pode ser usado para cobrir despesas de documentação ou para amortizar as parcelas futuras do seu consórcio. Existem regras específicas para cada tipo de bem, como a impossibilidade de usar a carta de imóveis para adquirir propriedades não regularizadas.`,
    `O que acontece se eu não puder mais pagar e precisar cancelar o consórcio? Você tem o direito de solicitar o cancelamento a qualquer momento. Contudo, a devolução dos valores pagos não é imediata. De acordo com a lei, a restituição ocorre em duas situações: quando sua cota cancelada é sorteada em uma assembleia específica para "excluídos" ou somente no final do prazo do grupo. Isso pode levar meses ou até anos. Além disso, o valor restituído não é integral. Corresponde ao que foi pago ao "Fundo Comum", mas com o desconto das taxas de administração já pagas e de uma multa por quebra de contrato. Essa política visa proteger a estabilidade do grupo, mas é a maior fonte de reclamações de consumidores.`,
    `Existe uma alternativa ao cancelamento para reaver meu dinheiro mais rápido? Sim. Vender ou transferir sua cota para outra pessoa é uma alternativa que pode ser mais vantajosa que o cancelamento. Ao encontrar um comprador interessado, você pode negociar os valores e recuperar seu investimento de forma mais rápida, e possivelmente com menor perda financeira do que no processo de cancelamento, que envolve multas e uma longa espera. A Rodobens é conhecida por ter um sistema de transferência considerado relativamente simples e eficiente, o que pode facilitar essa opção para quem precisa sair do grupo antes do fim do prazo.`,
    `A Rodobens é uma empresa confiável? A Rodobens é uma empresa com 75 anos de história e uma marca consolidada. Análises de agências de risco, como a Fitch Ratings, apontam um modelo de negócios sólido e estável. No entanto, seu perfil no Reclame Aqui, embora tenha nota ótima (8.5/10 e selo RA1000), revela que as principais queixas são sobre "Reembolso de valor pago" e "Demora na execução". Isso sugere que a empresa é muito eficaz em resolver problemas quando eles se tornam públicos, mas os canais de atendimento padrão podem ser uma fonte de atrito. A alta nota reflete uma excelente capacidade de resolução de reclamações, mas não necessariamente uma ausência de problemas nos processos do dia a dia.`,
    `Afinal, para quem o consórcio Rodobens é recomendado? O consórcio é altamente recomendado para pessoas com renda estável, disciplina para poupança a longo prazo, que não têm necessidade imediata do bem e cujo objetivo principal é economizar, fugindo dos juros de um financiamento. Para esse perfil, é uma ferramenta de planejamento poderosa. Por outro lado, apresenta riscos significativos para quem tem renda flutuante, pode precisar do dinheiro investido com rapidez (baixa liquidez), tem urgência na aquisição do bem ou não se sente confortável com a incerteza do prazo de contemplação e com a etapa final de análise de crédito.`,
    `Qual é o passo a passo da jornada de um consorciado? A jornada começa com a simulação e adesão a um grupo de consórcio, sem necessidade de análise de crédito inicial. Mensalmente, você paga a parcela para participar das assembleias, onde concorrerá à contemplação por sorteio. Se desejar, pode ofertar um lance para tentar antecipar o recebimento da carta de crédito. Uma vez contemplado, você passará por uma análise de crédito para confirmar sua capacidade de pagamento. Com o crédito aprovado, a carta é liberada para você comprar o bem à vista, negociando o melhor preço. Após a compra, você continua pagando as parcelas restantes até o encerramento do seu plano e a quitação total da cota.`,
  ];

  return new Response(data.join("\n ### \n"));
}

type Consorcio = {
  params: { slug: string[] };
};
